import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export const metadata = {
//   title: "IETE-SF | Induction '26",
//   description:
//     "Join IETE-SF and be part of a community to build, create, learn and connect.",
//   icons: {
//     icon: "/IETELOGO.svg",
//   },
// };

export const metadata = {
  title: "IETE-SF | Induction '26",
  description:
    "Join IETE-SF and be part of a community to build, create, learn and connect.",
  icons: {
    icon: [
      {
        url: "/ILGS.svg",
        sizes: "32x32",
        type: "image/svg+xml",
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
